# project definitions
project: doc
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Designed Mind
homepage_title: Designed Mind
site_title: Designed Mind
disqus_shortname: idrbwjekyll
google_analytics: UA-66296557-1

name:          Designed Mind
description:   Exploring the Virtual Cartesian Theatre of the mind
url:           http://designedmind.org
category-list: [code, editors, math, unix]

# variables

# sidebar_tagline: minddesign
sidebar_version: version 0.1

port: 4001

exclude:
  - doc_writer*
  - configs/
  - _site
  - di_multi*

# same for all
host: 127.0.0.1
feedback_email: roly.perera@dynamicaspects.org
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
