# project definitions
project: doc
audience: designers
product: all
platform: all
version: all
destination: /tmp/designedmind
topnav_title: Designed Mind 0.1
homepage_title: Designed Mind
site_title: Designed Mind
disqus_shortname: idrbwjekyll
google_analytics: UA-64811343-1

name:          Designed Mind
url:           http://designedmind.org

# variables

# sidebar_tagline: minddesign
# sidebar_version: version 0.1

port: 4000

exclude:
  - configs/
  - _site

# same for all
host: 127.0.0.1
feedback_email: roly.perera@dynamicaspects.org
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-blue.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "smart", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
